#!/usr/bin/env bash

set -e

if test ! $(which brew); then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew bundle --global --verbose | tee brew.log
composer global install --verbose | tee composer.log

# pecl e
# npm

echo 'Done! Checkout the log files'
