#!/usr/bin/env bash

set -e

if [ ! $(which brew) ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

logVersion=0

while [ -e "logs/brew.$logVersion.log" ]
do
    ((++logVersion))
done

brew bundle --global --verbose | tee logs/brew.$logVersion.log
composer global install --verbose | tee logs/composer.$logVersion.log

# pecl e
# npm

echo 'Done! Checkout the log files'
