# ~/.config/starship.toml

command_timeout = 6000
add_newline = false

[package]
format = "is [$symbol$version]($style) "
symbol = "📦 "
style = "208 bold"
display_private = true
disabled = false
version_format = "v${major}{minor}"
